<a href="https://colab.research.google.com/github/lilytong0919/NMA-shichimi-rulebreakerhalf-comparing-network/blob/main/explore_neuron_data_spc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# 1. Install the tool quietly
!pip install dandi --quiet

from dandi.download import download as dandi_download
import os
from google.colab import drive

# 2. Mount Google Drive for persistent storage
drive.mount('/content/drive')

# 3. Define a dedicated folder inside your Google Drive
drive_data_dir = "/content/drive/MyDrive/Dandi_Datasets/data"
os.makedirs(drive_data_dir, exist_ok=True)

filenames = [
    "sub-Dataset-3-Animals-1-to-4",
    "sub-Dataset-4-Animal-2-sess-1-to-7",
    "sub-Dataset-4-Animal-2-sess-8-to-12",
    "sub-Dataset-4-Animal-3-sess-1-to-6",
    "sub-Dataset-4-Animal-3-sess-7-to-11",
    "sub-Dataset-5-Animal-1",
    "sub-Dataset-5-Animals-2-ses-1-to-19",
    "sub-Dataset-5-Animals-2-ses-20-to-39",
    "sub-Dataset-5-Animals-2-ses-40-to-51",
    "sub-Dataset-5-Animals-3&4"
]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 398.2/398.2 kB 8.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.4/4.4 MB 68.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.2/194.2 kB 12.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.6/118.6 kB 7.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 362.3/362.3 kB 21.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.9/86.9 kB 6.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 58.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.1/53.1 kB 2.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.1/118.1 kB 7.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 284.1/284.1 kB 18.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.2/9.2 MB 63.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.9/43.9 MB 14.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.2/131.2 kB 7.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.7/61.7 kB 3.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.0/105.0 kB 7.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 331.1/331.1 kB 21.3 MB/s eta 0:00:00
Mounted at /content/drive

In [2]:
!python3 -m pip install pynapple --quiet

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 169.4/169.4 kB 3.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 712.5/712.5 kB 14.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 104.0/104.0 kB 5.0 MB/s eta 0:00:00

In [3]:
path_base = "/content/drive/MyDrive/Dandi_Datasets/data"

import pynapple as nap
import pandas as pd
import numpy as np

**Shared keys between 3 dataset are also:** (different spelling)
- 'EventTarget_Onset' (dataset 3 and 4), 'EventTarget_onset'(dataset 5)
- 'target_dir'(dataset 3 and 4), 'targets_dir'(dataset 5)

Shared keys only between dataset 4 and 5:
- 'cursor_vel_y',  'cursor_vel_x', 'cursor_pos_y', 'cursor_pos_x',  'cursor_acc_y',  'cursor_acc_x'

**Also between dataset 4 and 5:** (different spelling)
- 'target_ID' (dataset 4), 'Target_ID'(dataset 5)

In [42]:
import pickle
import os

# Assuming drive_data_dir is already defined and mounted
drive_data_dir = "/content/drive/MyDrive/Dandi_Datasets/data"

# Define the paths where the files were saved
df1_load_path = os.path.join(drive_data_dir, 'df1_Dataset-3-Animals-1-to-4.csv')
bin_load_path = os.path.join(drive_data_dir, 'bin1.pkl')

# Load df2 from CSV
if os.path.exists(df1_load_path):
    df1 = pd.read_csv(df1_load_path)
    print(f"df1 loaded from {df1_load_path}")
    display(df1.head())
else:
    print(f"df1 CSV file not found at {df1_load_path}")

# Load bin from pickle file
if os.path.exists(bin_load_path):
    with open(bin_load_path, 'rb') as f:
        bin = pickle.load(f)
    print(f"bin loaded from {bin_load_path}")
    print(f"Loaded bin value: {bin}")
else:
    print(f"bin pickle file not found at {bin_load_path}")

df1 loaded from /content/drive/MyDrive/Dandi_Datasets/data/df1_Dataset-3-Animals-1-to-4.csv

,Neuron0,Neuron1,Neuron2,Neuron3,Neuron4,Neuron5,Neuron6,Neuron7,Neuron8,Neuron9,...,animal,result,EventTarget_Onset,EventMovement_start,EventGo_cue,target_dir,hand_vel_y,hand_vel_x,date,brain_region
0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,...,1,R,False,False,False,0.0,1.0,3.0,20150313,M1
1,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,...,1,R,False,False,False,0.0,1.0,3.0,20150313,M1
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1,R,False,False,False,0.0,1.0,3.0,20150313,M1
3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1,R,False,False,False,0.0,1.0,3.0,20150313,M1
4,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1,R,False,False,False,0.0,-0.0,3.0,20150313,M1

bin loaded from /content/drive/MyDrive/Dandi_Datasets/data/bin1.pkl
Loaded bin value: 29.999999999999996

In [10]:
#bin=bin2
bin=30

**select animal**

In [36]:
#df_ani2_nospc = pd.concat([df2_nospc, df3_nospc,df4_nospc], ignore_index=True)
df1_anix = df1

print(f"Merged DataFrame shape: {df1_anix.shape}")

df1_anix=df1_anix[df1_anix['animal'] == 4]
df1_anix

Merged DataFrame shape: (1074509, 134)

,Neuron0,Neuron1,Neuron2,Neuron3,Neuron4,Neuron5,Neuron6,Neuron7,Neuron8,Neuron9,...,animal,result,EventTarget_Onset,EventMovement_start,EventGo_cue,target_dir,hand_vel_y,hand_vel_x,date,brain_region
484339,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4,R,False,False,False,0.785398,1.0,1.0,20171127,M1
484340,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4,R,False,False,False,0.785398,1.0,2.0,20171127,M1
484341,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,4,R,False,False,False,0.785398,1.0,2.0,20171127,M1
484342,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4,R,False,False,False,0.785398,1.0,3.0,20171127,M1
484343,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4,R,False,False,False,0.785398,1.0,3.0,20171127,M1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
872450,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4,R,False,False,False,0.785398,0.0,-0.0,20140307,PMd
872451,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,4,R,False,False,False,0.785398,0.0,-0.0,20140307,PMd
872452,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4,R,False,False,False,0.785398,0.0,-0.0,20140307,PMd
872453,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4,R,False,False,False,0.785398,0.0,-0.0,20140307,PMd
872454,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,4,R,False,False,False,0.785398,0.0,-0.0,20140307,PMd

In [37]:
np.unique(df1_anix['session'])

array([1, 2, 3, 4, 5, 6])

In [38]:
print('Unique values for each column in df_ani2_nospc:')
for col in df1_anix.columns:
    unique_vals = df1_anix[col].unique()
    print(f"Column '{col}': {unique_vals}")
    print(f"Number of unique values in '{col}': {len(unique_vals)}")
    print('-' * 30)

Unique values for each column in df_ani2_nospc:
Column 'Neuron0': [0. 1. 2. 3. 4. 5.]
Number of unique values in 'Neuron0': 6
------------------------------
Column 'Neuron1': [0. 1. 2. 3. 4. 5. 6. 7.]
Number of unique values in 'Neuron1': 8
------------------------------
Column 'Neuron2': [0. 1. 2. 3. 4. 5. 6.]
Number of unique values in 'Neuron2': 7
------------------------------
Column 'Neuron3': [0. 1. 2. 3. 4. 6. 5.]
Number of unique values in 'Neuron3': 7
------------------------------
Column 'Neuron4': [0. 1. 2. 3. 4.]
Number of unique values in 'Neuron4': 5
------------------------------
Column 'Neuron5': [0. 1. 2. 3. 4. 5. 6.]
Number of unique values in 'Neuron5': 7
------------------------------
Column 'Neuron6': [0. 1. 2. 3. 4.]
Number of unique values in 'Neuron6': 5
------------------------------
Column 'Neuron7': [0. 1. 2. 3. 4. 5. 6.]
Number of unique values in 'Neuron7': 7
------------------------------
Column 'Neuron8': [0. 1. 2. 3. 4. 5.]
Number of unique values in 'Neuron8': 6
------------------------------
Column 'Neuron9': [0. 1. 2. 3. 4. 5. 6.]
Number of unique values in 'Neuron9': 7
------------------------------
Column 'Neuron10': [1. 0. 2. 4. 3.]
Number of unique values in 'Neuron10': 5
------------------------------
Column 'Neuron11': [1. 0. 2. 3. 4. 5. 7. 6.]
Number of unique values in 'Neuron11': 8
------------------------------
Column 'Neuron12': [0. 1. 2. 3. 4. 5.]
Number of unique values in 'Neuron12': 6
------------------------------
Column 'Neuron13': [1. 2. 0. 3. 4. 5. 6.]
Number of unique values in 'Neuron13': 7
------------------------------
Column 'Neuron14': [0. 1. 2. 3. 5. 4. 6. 8.]
Number of unique values in 'Neuron14': 8
------------------------------
Column 'Neuron15': [1. 0. 2. 3. 4. 5. 6.]
Number of unique values in 'Neuron15': 7
------------------------------
Column 'Neuron16': [0. 1. 2. 3. 4. 5.]
Number of unique values in 'Neuron16': 6
------------------------------
Column 'Neuron17': [0. 1. 2. 3. 4. 5.]
Number of unique values in 'Neuron17': 6
------------------------------
Column 'Neuron18': [0. 1. 2. 3. 5. 4. 6.]
Number of unique values in 'Neuron18': 7
------------------------------
Column 'Neuron19': [ 0.  2.  1.  3.  4.  6.  5.  7.  8. 10.]
Number of unique values in 'Neuron19': 10
------------------------------
Column 'Neuron20': [0. 1. 2. 3. 4. 5. 6. 7.]
Number of unique values in 'Neuron20': 8
------------------------------
Column 'Neuron21': [0. 1. 2. 3. 4. 5. 6.]
Number of unique values in 'Neuron21': 7
------------------------------
Column 'Neuron22': [0. 1. 2. 3. 4. 5. 7.]
Number of unique values in 'Neuron22': 7
------------------------------
Column 'Neuron23': [0. 1. 2. 4. 3. 5. 6. 7. 8. 9.]
Number of unique values in 'Neuron23': 10
------------------------------
Column 'Neuron24': [0. 1. 2. 3. 4. 5. 6.]
Number of unique values in 'Neuron24': 7
------------------------------
Column 'Neuron25': [0. 1. 2. 3. 4. 5.]
Number of unique values in 'Neuron25': 6
------------------------------
Column 'Neuron26': [ 0.  2.  1.  3.  4.  6.  5.  8.  7. nan]
Number of unique values in 'Neuron26': 10
------------------------------
Column 'Neuron27': [ 0.  1.  2.  3.  4.  6.  5. nan]
Number of unique values in 'Neuron27': 8
------------------------------
Column 'Neuron28': [ 1.  0.  2.  3.  4.  5.  6. nan]
Number of unique values in 'Neuron28': 8
------------------------------
Column 'Neuron29': [ 0.  1.  2.  3.  4.  5. nan]
Number of unique values in 'Neuron29': 7
------------------------------
Column 'Neuron30': [ 1.  0.  2.  3.  4.  5.  7.  6.  9.  8. nan]
Number of unique values in 'Neuron30': 11
------------------------------
Column 'Neuron31': [ 0.  1.  2.  3.  4.  5.  7.  8.  6.  9. nan]
Number of unique values in 'Neuron31': 11
------------------------------
Column 'Neuron32': [ 0.  1.  2.  3.  4.  5. nan]
Number of unique values in 'Neuron32': 7
------------------------------
Column 'Neuron33': [ 0.  1.  2.  3.  4.  6.  5. nan]
Number of unique values in 'Neuron33': 8
------------------------------
Column 'Neuron34': [ 0.  1.  2.  3.  4.  5.  6. nan]
Number of unique values in 'Neuron34': 8
------------------------------
Column 'Neuron35': [ 0.  1.  2.  3.  4.  5. nan  6.  7.]
Number of unique values in 'Neuron35': 9
------------------------------
Column 'Neuron36': [ 0.  1.  2.  3.  4.  7.  5.  6. 10.  8. nan]
Number of unique values in 'Neuron36': 11
------------------------------
Column 'Neuron37': [ 0.  1.  2.  3.  4.  5. nan]
Number of unique values in 'Neuron37': 7
------------------------------
Column 'Neuron38': [ 1.  0.  2.  3.  4.  5. nan  6.]
Number of unique values in 'Neuron38': 8
------------------------------
Column 'Neuron39': [ 0.  1.  3.  2.  4. nan  5.]
Number of unique values in 'Neuron39': 7
------------------------------
Column 'Neuron40': [ 0.  1.  2.  3.  4. nan  5.  6.]
Number of unique values in 'Neuron40': 8
------------------------------
Column 'Neuron41': [ 0.  1.  2.  3. nan  4.  5.]
Number of unique values in 'Neuron41': 7
------------------------------
Column 'Neuron42': [ 0.  1.  2. nan  3.  4.  5.]
Number of unique values in 'Neuron42': 7
------------------------------
Column 'Neuron43': [ 1.  0.  2.  4.  3.  5.  6. nan]
Number of unique values in 'Neuron43': 8
------------------------------
Column 'Neuron44': [nan  0.  1.  2.  3.  4.]
Number of unique values in 'Neuron44': 6
------------------------------
Column 'Neuron45': [nan  0.  1.  2.  3.  4.]
Number of unique values in 'Neuron45': 6
------------------------------
Column 'Neuron46': [nan  0.  1.  2.  3.  4.]
Number of unique values in 'Neuron46': 6
------------------------------
Column 'Neuron47': [nan  0.  1.  2.  4.  3.  5.]
Number of unique values in 'Neuron47': 7
------------------------------
Column 'Neuron48': [nan  0.  1.  2.  3.  4.  5.]
Number of unique values in 'Neuron48': 7
------------------------------
Column 'Neuron49': [nan  0.  1.  2.  3.  4.  5.]
Number of unique values in 'Neuron49': 7
------------------------------
Column 'Neuron50': [nan  0.  1.  2.  4.  3.]
Number of unique values in 'Neuron50': 6
------------------------------
Column 'Neuron51': [nan  0.  1.  2.  3.  4.  5.]
Number of unique values in 'Neuron51': 7
------------------------------
Column 'Neuron52': [nan  0.  1.  2.  3.  4.]
Number of unique values in 'Neuron52': 6
------------------------------
Column 'Neuron53': [nan  0.  1.  2.  3.  4.  5.]
Number of unique values in 'Neuron53': 7
------------------------------
Column 'Neuron54': [nan  0.  1.  2.  3.  4.  5.  6.  7.]
Number of unique values in 'Neuron54': 9
------------------------------
Column 'Neuron55': [nan  0.  1.  2.  3.  5.  4.  8.]
Number of unique values in 'Neuron55': 8
------------------------------
Column 'Neuron56': [nan  0.  1.  2.  3.  4.  5.]
Number of unique values in 'Neuron56': 7
------------------------------
Column 'Neuron57': [nan  0.  1.  2.  3.  4.]
Number of unique values in 'Neuron57': 6
------------------------------
Column 'Neuron58': [nan  0.  1.  2.  3.  4.]
Number of unique values in 'Neuron58': 6
------------------------------
Column 'Neuron59': [nan  0.  1.  2.  3.  4.  6.]
Number of unique values in 'Neuron59': 7
------------------------------
Column 'Neuron60': [nan  1.  0.  2.  4.  3.]
Number of unique values in 'Neuron60': 6
------------------------------
Column 'Neuron61': [nan  0.  1.  2.  3.  4.  5.  6.]
Number of unique values in 'Neuron61': 8
------------------------------
Column 'Neuron62': [nan  0.  1.  2.  3.  4.  5.  6.]
Number of unique values in 'Neuron62': 8
------------------------------
Column 'Neuron63': [nan  0.  1.  2.  3.  4.  5.  6.  7.]
Number of unique values in 'Neuron63': 9
------------------------------
Column 'Neuron64': [nan  0.  2.  1.  3.  4.]
Number of unique values in 'Neuron64': 6
------------------------------
Column 'Neuron65': [nan  0.  1.  2.  3.  5.  4.]
Number of unique values in 'Neuron65': 7
------------------------------
Column 'Neuron66': [nan  0.  2.  1.  3.  5.  4.]
Number of unique values in 'Neuron66': 7
------------------------------
Column 'Neuron67': [nan  0.  1.  2.  3.  4.]
Number of unique values in 'Neuron67': 6
------------------------------
Column 'Neuron68': [nan  0.  1.  2.  3.  4.]
Number of unique values in 'Neuron68': 6
------------------------------
Column 'Neuron69': [nan  0.  1.  2.  3.  5.]
Number of unique values in 'Neuron69': 6
------------------------------
Column 'Neuron70': [nan  0.  1.  3.  2.  4.  6.  5.]
Number of unique values in 'Neuron70': 8
------------------------------
Column 'Neuron71': [nan  0.  1.  2.  4.  3.]
Number of unique values in 'Neuron71': 6
------------------------------
Column 'Neuron72': [nan  0.  1.  2.  3.]
Number of unique values in 'Neuron72': 5
------------------------------
Column 'Neuron73': [nan  0.  1.  2.  3.  4.]
Number of unique values in 'Neuron73': 6
------------------------------
Column 'Neuron74': [nan  0.  1.  2.  3.  4.  5.  6.]
Number of unique values in 'Neuron74': 8
------------------------------
Column 'Neuron75': [nan  0.  1.  2.  3.  4.]
Number of unique values in 'Neuron75': 6
------------------------------
Column 'Neuron76': [nan  0.  1.  2.  3.  4.  5.  6.]
Number of unique values in 'Neuron76': 8
------------------------------
Column 'Neuron77': [nan  0.  1.  2.  3.  4.]
Number of unique values in 'Neuron77': 6
------------------------------
Column 'Neuron78': [nan  0.  1.  2.  3.]
Number of unique values in 'Neuron78': 5
------------------------------
Column 'Neuron79': [nan  0.  1.  2.  3.  5.]
Number of unique values in 'Neuron79': 6
------------------------------
Column 'Neuron80': [nan  0.  2.  1.  3.]
Number of unique values in 'Neuron80': 5
------------------------------
Column 'Neuron81': [nan  0.  1.  2.  3.]
Number of unique values in 'Neuron81': 5
------------------------------
Column 'Neuron82': [nan  0.  1.  2.  3.  4.]
Number of unique values in 'Neuron82': 6
------------------------------
Column 'Neuron83': [nan  0.  1.  2.  3.  4.]
Number of unique values in 'Neuron83': 6
------------------------------
Column 'Neuron84': [nan  0.  1.  2.  3.  4.  5.]
Number of unique values in 'Neuron84': 7
------------------------------
Column 'Neuron85': [nan  0.  1.  2.  3.]
Number of unique values in 'Neuron85': 5
------------------------------
Column 'Neuron86': [nan  0.  1.  2.]
Number of unique values in 'Neuron86': 4
------------------------------
Column 'Neuron87': [nan  0.  1.  2.  5.  3.  4.]
Number of unique values in 'Neuron87': 7
------------------------------
Column 'Neuron88': [nan  0.  2.  1.]
Number of unique values in 'Neuron88': 4
------------------------------
Column 'Neuron89': [nan  0.  1.  3.  2.  8.  4.  5.]
Number of unique values in 'Neuron89': 8
------------------------------
Column 'Neuron90': [nan  0.  1.  2.  3.]
Number of unique values in 'Neuron90': 5
------------------------------
Column 'Neuron91': [nan  0.  1.  2.]
Number of unique values in 'Neuron91': 4
------------------------------
Column 'Neuron92': [nan  1.  0.  2.  4.  3.]
Number of unique values in 'Neuron92': 6
------------------------------
Column 'Neuron93': [nan  0.  1.  2.  3.  4.]
Number of unique values in 'Neuron93': 6
------------------------------
Column 'Neuron94': [nan  0.  1.  2.  3.  4.  5.]
Number of unique values in 'Neuron94': 7
------------------------------
Column 'Neuron95': [nan  0.  1.  2.  3.  4.]
Number of unique values in 'Neuron95': 6
------------------------------
Column 'Neuron96': [nan  0.  1.  2.  3.]
Number of unique values in 'Neuron96': 5
------------------------------
Column 'Neuron97': [nan  0.  1.  2.  3.]
Number of unique values in 'Neuron97': 5
------------------------------
Column 'Neuron98': [nan  0.  1.  2.  3.  5.  4.]
Number of unique values in 'Neuron98': 7
------------------------------
Column 'Neuron99': [nan  0.  1.  2.  3.  5.  4.]
Number of unique values in 'Neuron99': 7
------------------------------
Column 'Neuron100': [nan  0.  1.  2.  3.  4.]
Number of unique values in 'Neuron100': 6
------------------------------
Column 'Neuron101': [nan  0.  1.  2.  3.  4.]
Number of unique values in 'Neuron101': 6
------------------------------
Column 'Neuron102': [nan  0.  1.  2.  3.]
Number of unique values in 'Neuron102': 5
------------------------------
Column 'Neuron103': [nan  0.  1.  2.  3.  4.]
Number of unique values in 'Neuron103': 6
------------------------------
Column 'Neuron104': [nan  0.  1.  2.  3.  4.]
Number of unique values in 'Neuron104': 6
------------------------------
Column 'Neuron105': [nan  0.  1.  2.  3.  4.  5.]
Number of unique values in 'Neuron105': 7
------------------------------
Column 'Neuron106': [nan  0.  1.  2.  3.]
Number of unique values in 'Neuron106': 5
------------------------------
Column 'Neuron107': [nan  0.  1.  2.  3.]
Number of unique values in 'Neuron107': 5
------------------------------
Column 'Neuron108': [nan  1.  0.  2.  3.]
Number of unique values in 'Neuron108': 5
------------------------------
Column 'Neuron109': [nan  3.  1.  0.  2.  4.]
Number of unique values in 'Neuron109': 6
------------------------------
Column 'Neuron110': [nan  0.  1.  2.  3.]
Number of unique values in 'Neuron110': 5
------------------------------
Column 'Neuron111': [nan  0.  1.  2.  3.]
Number of unique values in 'Neuron111': 5
------------------------------
Column 'Neuron112': [nan  0.  1.  2.  3.]
Number of unique values in 'Neuron112': 5
------------------------------
Column 'Neuron113': [nan  0.  1.  2.  3.]
Number of unique values in 'Neuron113': 5
------------------------------
Column 'Neuron114': [nan  0.  1.  2.  3.]
Number of unique values in 'Neuron114': 5
------------------------------
Column 'Neuron115': [nan  0.  1.  2.  3.]
Number of unique values in 'Neuron115': 5
------------------------------
Column 'Neuron116': [nan  0.  1.  3.  2.]
Number of unique values in 'Neuron116': 5
------------------------------
Column 'Neuron117': [nan  0.  2.  1.]
Number of unique values in 'Neuron117': 4
------------------------------
Column 'Neuron118': [nan  0.  1.  2.  3.]
Number of unique values in 'Neuron118': 5
------------------------------
Column 'Neuron119': [nan  0.  1.  2.  3.  4.]
Number of unique values in 'Neuron119': 6
------------------------------
Column 'Neuron120': [nan  0.  1.  2.  3.  4.]
Number of unique values in 'Neuron120': 6
------------------------------
Column 'trial_id': [  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162
 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180
 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198
 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216
 217 218 219 220 221 222 223 224 225]
Number of unique values in 'trial_id': 225
------------------------------
Column 'session': [1 2 3 4 5 6]
Number of unique values in 'session': 6
------------------------------
Column 'datasetID': [3]
Number of unique values in 'datasetID': 1
------------------------------
Column 'animal': [4]
Number of unique values in 'animal': 1
------------------------------
Column 'result': ['R']
Number of unique values in 'result': 1
------------------------------
Column 'EventTarget_Onset': [False  True]
Number of unique values in 'EventTarget_Onset': 2
------------------------------
Column 'EventMovement_start': [False  True]
Number of unique values in 'EventMovement_start': 2
------------------------------
Column 'EventGo_cue': [False  True]
Number of unique values in 'EventGo_cue': 2
------------------------------
Column 'target_dir': [0.78539816 3.92699082 3.14159265 4.71238898 2.35619449 5.49778714
 1.57079633 0.        ]
Number of unique values in 'target_dir': 8
------------------------------
Column 'hand_vel_y': [  1.   2.   3.   4.   0.   6.   8.  10.  11.  13.  14.  12.   9.   7.
   5.  -1.  -2.  18.  21.  23.  22.  19.  15.  -3.  -4.  -5.  -6.  -7.
  -8.  -9. -10. -13. -16. -17. -18. -15. -12.  20.  17. -11. -20. -22.
 -23. -21. -19. -14. -82.  90. -24.  24.  16.  25.  27.  29.  28.  30.
  26. -27. -25.  32. -26.  34.  31.  33.  35.]
Number of unique values in 'hand_vel_y': 65
------------------------------
Column 'hand_vel_x': [   1.    2.    3.    4.    0.   -1.   -2.   -3.   -4.   -5.   -6.   -7.
   -8.    6.    9.   12.   14.   15.   16.   13.   11.   10.    8.    7.
   -9.  -10.  -11.  -13.  -12.  -15.  -16.  -17.    5.  -18.  -19.  -20.
  -14.  221. -216.   34.  -21.  -22.   18.   19.   20.   17.  -25.  -26.
  -27.  -23.   21.   24.   25.   23.   22.  -24.   26.   28.   27.  -28.
  -29.  -31.  -30.]
Number of unique values in 'hand_vel_x': 63
------------------------------
Column 'date': [20171127 20140218 20140303 20140304 20140306 20140307]
Number of unique values in 'date': 6
------------------------------
Column 'brain_region': ['M1' 'PMd']
Number of unique values in 'brain_region': 2
------------------------------

In [39]:
col_to_drop = [
 'trial_id',
 'session',
 'datasetID',
 'animal',
 'result',
 'EventTarget_Onset',
 'EventMovement_start',
 'EventGo_cue',
 'target_dir',
 'hand_vel_y',
 'hand_vel_x',
 'date',
 'brain_region']

In [40]:
display(df1_anix['animal'])
df1_anix_spc = df1_anix.drop(columns=col_to_drop, errors='ignore')
df1_anix_spc

484339    4
484340    4
484341    4
484342    4
484343    4
         ..
872450    4
872451    4
872452    4
872453    4
872454    4
Name: animal, Length: 388116, dtype: int64

,Neuron0,Neuron1,Neuron2,Neuron3,Neuron4,Neuron5,Neuron6,Neuron7,Neuron8,Neuron9,...,Neuron111,Neuron112,Neuron113,Neuron114,Neuron115,Neuron116,Neuron117,Neuron118,Neuron119,Neuron120
484339,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
484340,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
484341,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
484342,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
484343,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
872450,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
872451,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
872452,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
872453,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
872454,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
nan_columns = df1_anix_spc.columns[df1_anix_spc.isna().all()].tolist()
print("Columns in df1_anix_spc with all NaN values:")
if nan_columns:
    for col in nan_columns:
        print(col)
else:
    print("No columns found with all NaN values.")

Columns in df1_anix_spc with all NaN values:
No columns found with all NaN values.

In [43]:
import numpy as np
bin=30
# The 'bin' variable holds the time step in milliseconds. Convert it to seconds.
# 'bin' was previously determined to be 1.0 (ms) for this dataset.
time_step_s_df2 = bin / 1000

# Add a 'time_s' column to df2, representing actual time in seconds
df1['time_s'] = df1.index * time_step_s_df2
df1

,Neuron0,Neuron1,Neuron2,Neuron3,Neuron4,Neuron5,Neuron6,Neuron7,Neuron8,Neuron9,...,result,EventTarget_Onset,EventMovement_start,EventGo_cue,target_dir,hand_vel_y,hand_vel_x,date,brain_region,time_s
0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,...,R,False,False,False,0.000000,1.0,3.0,20150313,M1,0.00
1,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,...,R,False,False,False,0.000000,1.0,3.0,20150313,M1,0.03
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,R,False,False,False,0.000000,1.0,3.0,20150313,M1,0.06
3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,R,False,False,False,0.000000,1.0,3.0,20150313,M1,0.09
4,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,R,False,False,False,0.000000,-0.0,3.0,20150313,M1,0.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1074504,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,R,False,False,False,3.141593,-2.0,-34.0,20170917,Area2,32235.12
1074505,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,R,False,False,False,3.141593,-2.0,-38.0,20170917,Area2,32235.15
1074506,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,2.0,1.0,...,R,False,False,False,3.141593,-2.0,-40.0,20170917,Area2,32235.18
1074507,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,...,R,False,False,False,3.141593,-2.0,-39.0,20170917,Area2,32235.21
1074508,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,R,False,False,False,3.141593,-2.0,-36.0,20170917,Area2,32235.24

In [44]:
time_s_column = df1.pop('time_s')
df1.insert(0, 'time_s', time_s_column)
display(df1.head())

,time_s,Neuron0,Neuron1,Neuron2,Neuron3,Neuron4,Neuron5,Neuron6,Neuron7,Neuron8,...,animal,result,EventTarget_Onset,EventMovement_start,EventGo_cue,target_dir,hand_vel_y,hand_vel_x,date,brain_region
0,0.00,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,...,1,R,False,False,False,0.0,1.0,3.0,20150313,M1
1,0.03,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,...,1,R,False,False,False,0.0,1.0,3.0,20150313,M1
2,0.06,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1,R,False,False,False,0.0,1.0,3.0,20150313,M1
3,0.09,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1,R,False,False,False,0.0,1.0,3.0,20150313,M1
4,0.12,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1,R,False,False,False,0.0,-0.0,3.0,20150313,M1